# Kotlin系列微信公号样式
[style]
h1 = None
h2 = None
h3 = 2
h4 = 2
h5 = 1
image = None
li = None
link = None
p = 2
strong = None
table = None
ul = None
blockquote = None
codespan = None
codestyle = None
mac_window = None
header = None
footer = None
background = None